name       : liblttng-ust
version    : 2.9.0
release    : 1
source     :
    - http://lttng.org/files/lttng-ust/lttng-ust-2.9.0.tar.bz2 : 4d541a863f42dfc685ca05024027a442c70d03594c154a43e62bc109b1ea5daf
license    : LGPL-2.1
component  : programming.library
summary    : LTTng is an open source tracing framework for Linux. 
description: |
    LTTng is an open source tracing framework for Linux. 
builddeps  :
    - liburcu-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install