name       : liblttng-ust
version    : 2.12.2
release    : 3
source     :
    - https://lttng.org/files/lttng-ust/lttng-ust-2.12.2.tar.bz2 : bcd0f064b6ca88c72d84e760eac3472ae5c828411c634435922bee9fce359fc7
homepage   : https://lttng.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
summary    : Linux Trace Toolkit Next Generation User Space Tracer
description: |
    LTTng-UST, the Linux Trace Toolkit Next Generation Userspace Tracer, is port of the low-overhead tracing capabilities of the LTTng kernel tracer to user-space. The library enables tracing of applications and libraries.
builddeps  :
    - pkgconfig(liburcu)
    - pkgconfig(uuid)
    - asciidoc
    - xmlto
environment: |
    export PYTHON="/usr/bin/python3"
setup      : |
    %configure \
        --enable-man-pages \
        --disable-numa \
        --disable-examples \
        --enable-python-agent
build      : |
    %make
install    : |
    %make_install
